template for creating bash script with options, commands and arguments

diff --git a/example/bash/cli-with-options/bash-cli b/example/bash/cli-with-options/bash-cli
--- a/example/bash/cli-with-options/bash-cli
+++ b/example/bash/cli-with-options/bash-cli
@@ -1,55 +1,42 @@
 #!/bin/bash
 #
-# dbwebb: tool to manage course repos
+# A template for creating command line scripts taking options, commands
+# and arguments.
 #
-# exit values:
+# Exit values:
 #  0 on success
-#  1 on failing to carry out current command
-#  2 on bad usage
+#  1 on failure
 #
 
 
 
-#
+# Name of the script
+SCRIPT=$( basename "$0" )
+
 # Current version
-#
-DBW_VERSION="v1.9.5x (2015-06-17)"
+VERSION="1.0.0"
 
 
 
 #
 # Message to display for usage and help.
 #
-function usage ()
+function usage
 {
     local txt=(
-"Utility dbwebb for working with course repos: http://dbwebb.se/dbwebb-cli"
-"Usage: dbwebb [options] <command> [arguments]"
+"Utility $SCRIPT for doing stuff."
+"Usage: $SCRIPT [options] <command> [arguments]"
 ""
 "Command:"
-"  check             Check the environment."
-"  config            (Re-)Create config file."
-"  selfupdate        Update to latest version."
-"  sshkey            Create and install ssh-keys."
-"  login             Login to the remote server."
-"  clone [repo]      Clone a course repo."
-"  init              Init course repo and remote server."
-"  github [repo]     Get urls to repo on GitHub."
-"  update            Update course repo."
-"  upload [part]     Upload to server."
-"  download [part]   Download from server."
-"  create labid      Create a lab."
-"  validate [part]   Validate it."
-"  publish [part]    Publish it."
-"  inspect [course] [kmom] [user]  Inspect a kmom."
+"  command1             Demo of command."
+"  command2 [anything]  Demo of command using arguments."
+"  calendar [events]    Print out current calendar with events."
 ""
 "Options:"
-"  --inspect, -i  Help for inspect."
-"  --verbose, -v  More verbose."
-"  --yes, -y      Do not wait for my input."
 "  --help, -h     Print help."
-"  --version      Print version."
+"  --version, -h  Print version."
     )
+    
     printf "%s\n" "${txt[@]}"
 }
 
@@ -58,18 +45,16 @@ function usage ()
 #
 # Message to display when bad usage.
 #
-function badUsage ()
+function badUsage
 {
     local message="$1"
     local txt=(
 "For an overview of the command, execute:"
-"dbwebb --help"
+"$SCRIPT --help"
     )
     
-    if [[ "$message" ]]; then
-        printf "$message\n"
-    fi
-    
+    [[ $message ]] && printf "$message\n"
+
     printf "%s\n" "${txt[@]}"
 }
 
@@ -78,30 +63,57 @@ function badUsage ()
 #
 # Message to display for version.
 #
-function version ()
+function version
 {
     local txt=(
-"dbwebb version $DBW_VERSION"
+"$SCRIPT version $VERSION"
     )
+
     printf "%s\n" "${txt[@]}"
 }
 
 
 
 #
-# Create default files.
+# Function for taking care of specific command. Name the function as the
+# command is named.
 #
-function dbwebb-init-me()
+function app-command1
 {
-    local meDefault="$DBW_COURSE_DIR/.default/"
-    local me="$DBW_COURSE_DIR/me/"
+    echo "This is output from command1."
+}
 
-    local intro="Creating and initiating the directory 'me/' by copying directory structure and files from the directory '.default/' (will not overwrite existing files)."
-    local command="rsync -av --exclude README.md --ignore-existing \"$meDefault\" \"$me\""
-    local message="to init the directory 'me/'."
 
-    checkIfValidCourseRepoOrExit
-    executeCommand "$intro" "$command" "$message"
+
+#
+# Function for taking care of specific command. Name the function as the
+# command is named.
+#
+function app-command2
+{
+    echo "This is output from command2."
+    echo "Command 2 takes additional arguments which currently are:"
+    echo " Number of arguments = '$#'"
+    echo " List of arguments = '$*'"
+}
+
+
+
+#
+# Function for taking care of specific command. Name the function as the
+# command is named.
+#
+function app-calendar
+{
+    local events="$1"
+    
+    echo "This is output from command3, showing the current calender."
+    cal
+    
+    if [ "$events" = "events" ]; then
+        echo
+        calendar
+    fi
 }
 
 
@@ -123,18 +135,18 @@ do
             exit 0
         ;;
 
-        update         \
-        | check        \
-        | init-me)
+        command1         \
+        | command2       \
+        | calendar)
             command=$1
             shift
-            dbwebb-$command $*
+            app-$command $*
             exit 0
         ;;
         
         *)
             badUsage "$MSG_FAILED Option/command not recognized."
-            exit 2
+            exit 1
         ;;
         
     esac
